"""initial migration

Revision ID: 6447cb759011
Revises:
Create Date: 2026-02-18 08:00:38.568079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6447cb759011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_messages_conversation_id",   # ✅ Name added
            "conversations",
            ["conversation_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_messages_conversation_id",   # ✅ Same name here
            type_="foreignkey"
        )
    # ### end Alembic commands ###
