"""Add follow_request_id to notifications table

Revision ID: add_follow_request_id_to_notifications
Revises: notification_update
Create Date: 2025-11-09 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_follow_request_id_to_notifications'
down_revision = 'notification_update'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('follow_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_notifications_follow_request_id', 'notifications', 'follow_requests', ['follow_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_follow_request_id', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'follow_request_id')
    # ### end Alembic commands ###