"""Follow system update

Revision ID: follow_system_update
Revises: 
Create Date: 2025-11-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'follow_system_update'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create follow_requests table
    op.create_table('follow_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_user_id', sa.String(), nullable=False),
        sa.Column('to_user_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_follow_request')
    )
    
    # Create followers table
    op.create_table('followers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('follower_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'follower_id', name='uq_follower')
    )
    
    # Modify notifications table
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=True))
    op.drop_column('notifications', 'content')
    op.add_column('notifications', sa.Column('read_status', sa.Boolean(), nullable=True))
    op.drop_column('notifications', 'read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop followers table
    op.drop_table('followers')
    
    # Drop follow_requests table
    op.drop_table('follow_requests')
    
    # Revert notifications table
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'message')
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'read_status')
    # ### end Alembic commands ###