"""Notification table update

Revision ID: notification_update
Revises: follow_system_update
Create Date: 2025-11-07 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'notification_update'
down_revision = 'follow_system_update'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify notifications table to match new model
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=True))
    op.drop_column('notifications', 'content')
    op.add_column('notifications', sa.Column('read_status', sa.Boolean(), nullable=True))
    op.drop_column('notifications', 'read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert notifications table
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'message')
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'read_status')
    # ### end Alembic commands ###